apiVersion: apps/v1
kind: Deployment
metadata:
  name: testaudisoft-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testaudisoft-api
  template:
    metadata:
      labels:
        app: testaudisoft-api
    spec:
      containers:
        - name: testaudisoft-api
          image: testaudisoft-testaudisoft_api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: ConnectionStrings__DefaultConnection
              value: Host=testaudisoft-postgres;Port=5432;Database=TestAudisoftDb;Username=admin;Password=1234