apiVersion: v1
kind: Service
metadata:
  name: testaudisoft-postgres
spec:
  type: NodePort
  selector:
    app: testaudisoft-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: 30433